---
version: '2'

project_name: run-cli

builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    go_version: 1.25.5

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

brews:
  - name: rabdis
    tap:
      owner: JulienBreux
      name: run-cli-homebrew
    commit_author:
      name: Julien Breux
      email: julien.breux@gmail.com
    folder: Formula
    homepage: https://github.com/julienbreux/run-cli/
    description: Run CLI is an interactive CLI to manage your Google Cloud Run resources with panache!
    test: system "run version"

dockers:
  - image_templates: ["JulienBreux/run-cli:{{ .Version }}"]
    dockerfile: Dockerfile
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://gitlab.com/JulienBreux/run-cli
      - --label=org.opencontainers.image.source=https://gitlab.com/JulienBreux/run-cli
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0

nfpm:
  - maintainer: Julien Breux <julien.breux@gmail.com>
    description: Run CLI.
    homepage: https://gitlab.com/JulienBreux/run-cli
    license: Apache-2.0
    formats:
      - deb
      - rpm
      - apk
